services:
  xceliqos_db:
    image: postgres:15-alpine
    container_name: xceliqos_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=xceliq
    volumes:
      - pgdata:/var/lib/postgresql/data

  api-gateway:
    build:
      context: ./backend
      dockerfile: api-gateway/Dockerfile
    env_file:
      - ./backend/api-gateway/.env
    ports:
      - "3000:3000"
    depends_on:
      - xceliqos_db

  school-service:
    build:
      context: ./backend
      dockerfile: school-service/Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - xceliqos_db

  ai-service:
    build:
      context: ./backend
      dockerfile: ai-service/Dockerfile
    env_file:
      - ./backend/ai-service/.env
    depends_on:
      - xceliqos_db

  auth-service:
    build:
      context: ./backend
      dockerfile: auth-service/Dockerfile
    env_file:
      - ./backend/auth-service/.env
    ports:
      - "3002:3002"
    depends_on:
      - xceliqos_db

  frontend:
    build:
      context: ./frontend/school-portal
      dockerfile: Dockerfile
    ports:
      - "5173:5175"
    environment:
      - VITE_API_URL=http://api-gateway:3000
    depends_on:
      - api-gateway

volumes:
  pgdata: