services:
  lumiqos_db:
    image: postgres:15-alpine
    container_name: lumiqos_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lumiq
    volumes:
      - pgdata:/var/lib/postgresql/data

  api-gateway:
    build:
      context: ./backend
      dockerfile: api-gateway/Dockerfile
    env_file:
      - ./backend/api-gateway/.env
    ports:
      - "3000:3000"
    depends_on:
      - lumiqos_db

  school-service:
    build:
      context: ./backend
      dockerfile: school-service/Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - lumiqos_db

  ai-service:
    build:
      context: ./backend
      dockerfile: ai-service/Dockerfile
    depends_on:
      - lumiqos_db

  frontend:
    build:
      context: ./frontend/school-portal
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - api-gateway

volumes:
  pgdata: