import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialBillingSchema1776348938166 implements MigrationInterface {
    name = 'InitialBillingSchema1776348938166'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "role" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "role_id" character varying, "role_name" character varying, "description" text, CONSTRAINT "UQ_df46160e6aa79943b83c81e496e" UNIQUE ("role_id"), CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password_hash" character varying, "first_name" character varying, "last_name" character varying, "user_id" character varying, "school_id" character varying, "role_id" character varying, "status" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "school" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "school_name" character varying, "school_id" character varying, "school_code" character varying, "country" character varying, "region" character varying, "timezone" character varying, "board" character varying, CONSTRAINT "PK_57836c3fe2f2c7734b20911755e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "time_slots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" uuid NOT NULL, "name" character varying NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f87c73d8648c3f3f297adba3cb8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tenant_subscription" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "plan_id" character varying, "school_id" character varying, "status" character varying, "current_period_end" TIMESTAMP, CONSTRAINT "PK_d91b66c187ed664d890944a9776" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "class" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying, "class_name" character varying NOT NULL, "class_id" uuid, "school_id" uuid NOT NULL, "grade_level" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1389cb6bf60ba3b2b7234b75b91" UNIQUE ("school_id", "class_name"), CONSTRAINT "PK_0b9024d21bdfba8b1bd1c300eae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "section" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "section_name" character varying, "section_id" uuid, "class_id" uuid, "school_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3c41d2d699384cc5e8eac54777d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "boards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "country" character varying NOT NULL DEFAULT 'India', "exam_buffer_days" integer NOT NULL DEFAULT '7', "revision_days" integer NOT NULL DEFAULT '14', "max_sessions_per_day" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_606923b0b068ef262dfdcd18f44" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subject" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "subject_name" character varying, "subject_id" character varying, "school_id" character varying, "board_id" uuid, "category" character varying NOT NULL DEFAULT 'CORE', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_12eee115462e38d62e5455fc054" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teacher_subject" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" character varying, "teacher_id" uuid, "subject_id" uuid, "class_id" uuid, "section_id" uuid, "periods_per_day" double precision NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2f09d6cc99fa8017094fb186ce9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teaching_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" uuid NOT NULL, "teacher_id" uuid NOT NULL, "class_id" uuid NOT NULL, "subject_id" uuid NOT NULL, "date" date NOT NULL, "topics_covered" json NOT NULL, "actual_sessions" integer NOT NULL DEFAULT '1', "remarks" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0b1778c6cebf31daddab6d49c42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "syllabus_topic" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "syllabus_id" uuid NOT NULL, "topic_name" character varying NOT NULL, "sequence" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fa0b73e14094685fa5bdcd7805e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "syllabus" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" uuid NOT NULL, "class_id" uuid NOT NULL, "subject_id" uuid NOT NULL, "units" integer NOT NULL, "estimated_days" integer NOT NULL, "total_topics" integer NOT NULL DEFAULT '0', "current_topic" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5205bdbdb2d719615ccf5eabfb5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "student" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "email" character varying, "student_id" character varying, "lumiq_id" character varying, "school_id" uuid, "admission_number" character varying, "status" character varying, "xp" integer NOT NULL DEFAULT '0', "level" integer NOT NULL DEFAULT '1', "streak_days" integer NOT NULL DEFAULT '0', "skill_tree" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fedf76a84e2cfe30e86ca7bb943" UNIQUE ("lumiq_id"), CONSTRAINT "PK_3d8016e1cb58429474a3c041904" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "student_marks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "marks_id" character varying, "student_id" character varying, "school_id" character varying, "exam_subject_id" character varying, "marks_obtained" double precision, "status" character varying, "grade" character varying, "remarks" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2b0b8fff6a616d090e7d6c109a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "student_learning_profile" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "PK_47e8fa767e060967f520433dfb5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "student_health_record" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "PK_1d3d7851bd98accc82150685d0d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "student_guardian" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "student_id" character varying, "user_id" character varying, "school_id" character varying, "is_primary" boolean NOT NULL DEFAULT false, "relationship" character varying, CONSTRAINT "PK_9835070fcc474de5e2e25fe8060" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "student_fee_account" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "student_id" character varying, "academic_year_id" character varying, "school_id" character varying, "total_fee" numeric(10,2) NOT NULL DEFAULT '0', "balance" numeric(10,2) NOT NULL DEFAULT '0', "discount" numeric(10,2) NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7df0ccf8b176743e04664bd7f6a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "student_enrollment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "admission_number" character varying NOT NULL, "enrollment_id" character varying, "student_id" uuid, "school_id" uuid, "academic_year_id" uuid, "class_id" uuid, "section_id" uuid, "roll_number" character varying, "status" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8d2ebd470040ec79545843248c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "student_document" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "student_id" character varying, "school_id" character varying, CONSTRAINT "PK_2c9db77bec5d1700ab0db7d6476" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attendance_session" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "session_id" character varying, "school_id" uuid, "academic_year_id" uuid, "class_id" uuid, "section_id" uuid, "subject_id" uuid, "session_date" TIMESTAMP, CONSTRAINT "PK_5940f7beb6d791a618dbf88361e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "student_attendance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "session_id" uuid, "student_id" character varying, "school_id" character varying, "status" character varying, "remarks" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_432904873d2981c3443763ef49d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "academic_year" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "academic_year_id" uuid, "year_name" character varying, "school_id" uuid, "start_date" TIMESTAMP, "end_date" TIMESTAMP, "status" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ebe672580520ed92b9e89088325" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."school_calendar_day_type_enum" AS ENUM('Teaching_Day', 'Holiday', 'Activity_Day', 'Exam_Day', 'Pre_Exam', 'Post_Event', 'Buffer_Day', 'Bagless_Day')`);
        await queryRunner.query(`CREATE TABLE "school_calendar" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" uuid NOT NULL, "academic_year_id" uuid NOT NULL, "date" date NOT NULL, "day_type" "public"."school_calendar_day_type_enum" NOT NULL DEFAULT 'Teaching_Day', "is_working_day" boolean NOT NULL DEFAULT true, "description" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_579fc4d2e767404c39c6b3b0dc2" UNIQUE ("school_id", "date"), CONSTRAINT "PK_cfe545fe11d8f840e8e689c2243" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "saas_plan" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "plan_id" character varying, "max_students" integer, "max_teachers" integer, "ai_features_enabled" boolean NOT NULL DEFAULT false, "analytics_enabled" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_15511541375f7f31f53b082dc6d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permission" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "permission_id" character varying, "module" character varying, "action" character varying, CONSTRAINT "UQ_aaa6d61e22fb453965ae6157ce5" UNIQUE ("permission_id"), CONSTRAINT "PK_3b8b97af9d9d8807e41e6f48362" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permission" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role_id" character varying, "permission_id" character varying, CONSTRAINT "PK_96c8f1fd25538d3692024115b47" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "exam" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "exam_id" character varying, "name" character varying NOT NULL, "school_id" uuid, "academic_year_id" uuid, "status" character varying, "start_date" date, "end_date" date, "exam_type_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_56071ab3a94aeac01f1b5ab74aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "report_card" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "report_card_id" character varying, "school_id" uuid, "student_id" uuid, "exam_id" uuid, "class_id" uuid, "section_id" uuid, "total_marks" double precision, "percentage" double precision, "rank" integer, "status" character varying NOT NULL DEFAULT 'published', "is_signed_by_principal" boolean NOT NULL DEFAULT false, "principal_signed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f9f78b27d878b6e9d43755d1f0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "report_card_subject" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "report_card_id" character varying, "school_id" character varying, CONSTRAINT "PK_39dc78423554247741472e4561a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."planning_day_type_enum" AS ENUM('WORKING', 'HOLIDAY', 'EXAM', 'REVISION')`);
        await queryRunner.query(`CREATE TABLE "planning_day" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" character varying NOT NULL, "academic_year_id" character varying NOT NULL, "date" date NOT NULL, "type" "public"."planning_day_type_enum" NOT NULL, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_88d9d717eb23afcf39f7ab274dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_970515f10ff41d260af28738d2" ON "planning_day" ("school_id", "academic_year_id", "date") `);
        await queryRunner.query(`CREATE TABLE "curriculum_units" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" uuid NOT NULL, "subject_id" uuid NOT NULL, "title" character varying NOT NULL, "weightage" integer NOT NULL DEFAULT '0', "sequence_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_70a9c6c35eccc217975dc9ce81b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lesson_plans_v3" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" uuid NOT NULL, "class_id" uuid NOT NULL, "subject_id" uuid NOT NULL, "teacher_id" uuid NOT NULL, "title" character varying NOT NULL, "learning_outcome" text, "estimated_minutes" integer NOT NULL DEFAULT '40', "complexity_index" integer NOT NULL DEFAULT '5', "unit_id" uuid, "plan_data" jsonb, "tags" text array NOT NULL DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a46dd2690b6e4b89d748d0453b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."planned_schedule_status_enum" AS ENUM('Scheduled', 'Completed', 'Delayed', 'Skipped')`);
        await queryRunner.query(`CREATE TABLE "planned_schedule" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" uuid NOT NULL, "academic_year_id" uuid NOT NULL, "section_id" uuid, "lesson_id" uuid, "calendar_id" uuid, "class_id" uuid NOT NULL, "subject_id" uuid NOT NULL, "planned_date" date NOT NULL, "actual_completion_date" date, "deviation_days" integer NOT NULL DEFAULT '0', "title_override" character varying, "teacher_id" uuid, "slot_id" uuid, "status" "public"."planned_schedule_status_enum" NOT NULL DEFAULT 'Scheduled', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_985be20d5e87317a389112e52b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "academic_plan" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" uuid NOT NULL, "academic_year_id" uuid NOT NULL, "class_id" uuid, "subject_id" uuid, "version" integer NOT NULL DEFAULT '1', "is_baseline" boolean NOT NULL DEFAULT false, "parent_plan_id" uuid, "status" character varying NOT NULL DEFAULT 'draft', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c3b4a50396aaa5dc4880c9e8f5c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "planning_calendar" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "plan_id" uuid NOT NULL, "date" date NOT NULL, "type" character varying NOT NULL, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_df781c7f02c731bacafde50ae1b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "period_configuration" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" character varying NOT NULL, "academic_year_id" character varying, "config" jsonb NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3a35624c665806fd7f61da962df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "notification_id" character varying, "title" character varying, "message" text NOT NULL, "type" character varying, "school_id" character varying, "created_by" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification_recipient" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "notification_id" uuid, "user_id" character varying, "recipient_id" character varying, "school_id" character varying, "read_status" character varying, "delivery_status" character varying, "sent_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9830357f52360a126737d498e66" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "message_id" character varying, "thread_id" character varying, "school_id" character varying, "sender_id" character varying, "content" text, "message_text" text, "sent_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ba01f0a3e0123651915008bc578" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "message_thread" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "thread_id" character varying, "school_id" character varying, "teacher_id" character varying, "student_id" uuid, "created_by" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_11cb07b9ecf8cb247c5e2dc86ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" uuid NOT NULL, "name" character varying NOT NULL, "category" character varying NOT NULL, "current_stock" integer NOT NULL, "unit" character varying NOT NULL, "usage_rate" character varying NOT NULL, "run_out_prediction" character varying, "status" character varying NOT NULL DEFAULT 'Healthy', "vendor" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_94f5cbcb5f280f2f30bd4a9fd90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "homework_assignment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "homework_id" character varying, "title" character varying NOT NULL, "type" character varying NOT NULL DEFAULT 'homework', "reward_xp" integer NOT NULL DEFAULT '0', "skill_category" character varying, "school_id" character varying, "teacher_id" character varying, "class_id" character varying, "section_id" character varying, "subject_id" character varying, "assigned_date" TIMESTAMP, "due_date" TIMESTAMP, "attachment_url" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_588a2f1ac43b400bc42a46af1ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "homework_submission" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "submission_id" character varying, "homework_id" uuid, "student_id" character varying, "school_id" character varying, "submission_text" text, "submission_file_url" character varying, "teacher_remark" text, "teacher_feedback" text, "submission_data" jsonb, "grade" character varying, "graded_at" TIMESTAMP, "submitted_at" TIMESTAMP, "status" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_77748553ef7235189268bfa5e3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "grade_scale" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" character varying, "min_marks" double precision, "max_marks" double precision, "grade" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9f5b85a39ac18a63be2f35ee73a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fee_structure" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a32d707ce58ab84c493b492cfc5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fee_invoice" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_id" character varying, "student_id" character varying, "academic_year_id" character varying, "fee_category_id" character varying, "school_id" character varying, "amount" numeric(10,2) NOT NULL, "remaining_balance" numeric(10,2) NOT NULL DEFAULT '0', "due_date" TIMESTAMP, "status" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_626d6dee0507ce86d785090556c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "exam_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "school_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_268e5eb3103fefc3bc1faffaf0f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "exam_subject" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "exam_subject_id" character varying, "exam_id" uuid, "subject_id" character varying, "school_id" character varying, "class_id" character varying, "section_id" character varying, "max_marks" double precision, "ai_questions" jsonb, "bloom_taxonomy" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_14c2f71a4dd7823c96d39b13757" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "curriculum_plan_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "plan_id" uuid NOT NULL, "topic_id" uuid, "planned_date" date NOT NULL, "planned_sessions" integer NOT NULL DEFAULT '1', "status" character varying NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a95a9b5ae50971719c416954bdc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "curriculum_plan" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" uuid NOT NULL, "academic_year_id" uuid NOT NULL, "class_id" uuid NOT NULL, "subject_id" uuid NOT NULL, "total_topics" integer NOT NULL, "total_estimated_hours" integer NOT NULL, "planned_start_date" date NOT NULL, "planned_end_date" date NOT NULL, "status" character varying NOT NULL DEFAULT 'draft', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4086c8a693f15aa9a85a563aa5a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "curriculum_mapping" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" uuid NOT NULL, "class_id" uuid NOT NULL, "subject_id" uuid NOT NULL, "teacher_id" uuid NOT NULL, "lesson_plan_id" uuid, "mapping_date" date NOT NULL, "topic" character varying NOT NULL, "unit_number" integer NOT NULL DEFAULT '1', "status" character varying NOT NULL DEFAULT 'scheduled', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b9532f94e2584a935844ac6fd4e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "board_config" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "board_name" character varying NOT NULL, "exam_buffer_days" integer NOT NULL DEFAULT '7', "revision_days" integer NOT NULL DEFAULT '14', "max_sessions_per_day" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1636b437b1255b668e371bc8e23" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "analytics_snapshot" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "PK_2582bc929d92e767c20aad93d20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "academic_plan_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "plan_id" uuid NOT NULL, "class_id" uuid NOT NULL, "subject_id" uuid NOT NULL, "topic_index" integer NOT NULL, "planned_date" date NOT NULL, "session_count" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4c05955c282fa0e06ba42b80419" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "academic_calendar_event" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" uuid NOT NULL, "academic_year_id" uuid NOT NULL, "month_index" integer NOT NULL, "month_name" character varying NOT NULL, "working_days" integer array NOT NULL DEFAULT '{}', "events" jsonb, "status" character varying NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e8c87b9820312cc12bf2ea1bdbe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fee_payment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_id" uuid NOT NULL, "amount" numeric(10,2) NOT NULL, "school_id" character varying, "payment_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_04a477e9910932c09e80e282d36" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fee_category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "school_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ea102044cbccad1a2f3a96830f7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_fb2e442d14add3cefbdf33c4561" FOREIGN KEY ("role_id") REFERENCES "role"("role_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_slots" ADD CONSTRAINT "FK_b1ecb91960ccb14bbfe23d06822" FOREIGN KEY ("school_id") REFERENCES "school"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subject" ADD CONSTRAINT "FK_bbaf2b061bfcebe55de663778cd" FOREIGN KEY ("board_id") REFERENCES "boards"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teacher_subject" ADD CONSTRAINT "FK_2a9d30cb4207da7ddf7c109097a" FOREIGN KEY ("teacher_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teacher_subject" ADD CONSTRAINT "FK_9637c243e0ff941fd4a3389241b" FOREIGN KEY ("class_id") REFERENCES "class"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teacher_subject" ADD CONSTRAINT "FK_7015c3aa4353ae609d1a06492f7" FOREIGN KEY ("section_id") REFERENCES "section"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teacher_subject" ADD CONSTRAINT "FK_c876c0444684d4812824989ba2c" FOREIGN KEY ("subject_id") REFERENCES "subject"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teaching_log" ADD CONSTRAINT "FK_2882964b8a6ff3a913435668c18" FOREIGN KEY ("school_id") REFERENCES "school"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teaching_log" ADD CONSTRAINT "FK_0beaa28dcebe2f458d63e5c9d03" FOREIGN KEY ("teacher_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teaching_log" ADD CONSTRAINT "FK_bdf3f3a380ee1cae102cfa1e88a" FOREIGN KEY ("class_id") REFERENCES "class"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teaching_log" ADD CONSTRAINT "FK_1a2f55871a41820e51d9506b470" FOREIGN KEY ("subject_id") REFERENCES "subject"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus_topic" ADD CONSTRAINT "FK_89a78f9852aa598ca6a5e0805fb" FOREIGN KEY ("syllabus_id") REFERENCES "syllabus"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus" ADD CONSTRAINT "FK_76d1df4a0706f0a9436a532d07a" FOREIGN KEY ("school_id") REFERENCES "school"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus" ADD CONSTRAINT "FK_98f18ccb8e3f01f8051ca8ae477" FOREIGN KEY ("class_id") REFERENCES "class"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus" ADD CONSTRAINT "FK_84076f08bebb15b7ae885440ae3" FOREIGN KEY ("subject_id") REFERENCES "subject"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_enrollment" ADD CONSTRAINT "FK_233f8bd7ce6e3c0cd5ba4f6ea4d" FOREIGN KEY ("class_id") REFERENCES "class"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_enrollment" ADD CONSTRAINT "FK_2f5361abfa1e5bc086a51f28bd8" FOREIGN KEY ("section_id") REFERENCES "section"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_attendance" ADD CONSTRAINT "FK_a042a5b12717cae570c763acbd0" FOREIGN KEY ("session_id") REFERENCES "attendance_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "school_calendar" ADD CONSTRAINT "FK_91006758c742b253e5c3526061b" FOREIGN KEY ("school_id") REFERENCES "school"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "school_calendar" ADD CONSTRAINT "FK_23c9ce15950639eba08af82725a" FOREIGN KEY ("academic_year_id") REFERENCES "academic_year"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf" FOREIGN KEY ("permission_id") REFERENCES "permission"("permission_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368" FOREIGN KEY ("role_id") REFERENCES "role"("role_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_card" ADD CONSTRAINT "FK_24d288a1b1ea550277955d41b6d" FOREIGN KEY ("exam_id") REFERENCES "exam"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curriculum_units" ADD CONSTRAINT "FK_97b4269e7d7c01c585ab0efe2da" FOREIGN KEY ("school_id") REFERENCES "school"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curriculum_units" ADD CONSTRAINT "FK_344206ea52885d57b6b5b495b3f" FOREIGN KEY ("subject_id") REFERENCES "subject"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_plans_v3" ADD CONSTRAINT "FK_96b565574eb7cb6c049d920630f" FOREIGN KEY ("unit_id") REFERENCES "curriculum_units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_plans_v3" ADD CONSTRAINT "FK_57f87263653fd68f21303d08dff" FOREIGN KEY ("school_id") REFERENCES "school"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_plans_v3" ADD CONSTRAINT "FK_cf859f5d7ca538cb0c9c746f008" FOREIGN KEY ("class_id") REFERENCES "class"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_plans_v3" ADD CONSTRAINT "FK_76cbb1cd011b2089abf8a5015d7" FOREIGN KEY ("subject_id") REFERENCES "subject"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_plans_v3" ADD CONSTRAINT "FK_48dd2eaa16cf18435a4fe368515" FOREIGN KEY ("teacher_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "planned_schedule" ADD CONSTRAINT "FK_11058662640de7fd783447e53e4" FOREIGN KEY ("school_id") REFERENCES "school"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "planned_schedule" ADD CONSTRAINT "FK_2fadfa26be2b4160891ad8cb850" FOREIGN KEY ("academic_year_id") REFERENCES "academic_year"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "planned_schedule" ADD CONSTRAINT "FK_b1c2b3ba3034a3835177dda6252" FOREIGN KEY ("lesson_id") REFERENCES "lesson_plans_v3"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "planned_schedule" ADD CONSTRAINT "FK_e308eba733f6be1ab402d2bd16c" FOREIGN KEY ("calendar_id") REFERENCES "school_calendar"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "planned_schedule" ADD CONSTRAINT "FK_fabfae67b685b6c318a7d531643" FOREIGN KEY ("class_id") REFERENCES "class"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "planned_schedule" ADD CONSTRAINT "FK_54962f5cc9e1bd4bf22b1e4b276" FOREIGN KEY ("subject_id") REFERENCES "subject"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "planned_schedule" ADD CONSTRAINT "FK_c3946f1eb385e02dd6b39dacc64" FOREIGN KEY ("teacher_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "planned_schedule" ADD CONSTRAINT "FK_0df06b70ec3b7dcae5a663ab5be" FOREIGN KEY ("slot_id") REFERENCES "time_slots"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "planning_calendar" ADD CONSTRAINT "FK_e09b1caf6bf47a24e5d4eead82a" FOREIGN KEY ("plan_id") REFERENCES "academic_plan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_recipient" ADD CONSTRAINT "FK_f6ebcb1bb7f7f55e33cf8488065" FOREIGN KEY ("notification_id") REFERENCES "notification"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_thread" ADD CONSTRAINT "FK_70c5b0368192c822fd197144306" FOREIGN KEY ("student_id") REFERENCES "student"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_item" ADD CONSTRAINT "FK_4d2125c70a8b37c0d2bca236f40" FOREIGN KEY ("school_id") REFERENCES "school"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "homework_submission" ADD CONSTRAINT "FK_ea42144388e4f52a623cb9ddedd" FOREIGN KEY ("homework_id") REFERENCES "homework_assignment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exam_subject" ADD CONSTRAINT "FK_096e1a3aecf719dd5964e33b573" FOREIGN KEY ("exam_id") REFERENCES "exam"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curriculum_plan_item" ADD CONSTRAINT "FK_76763a7dae55bc95b9515642736" FOREIGN KEY ("plan_id") REFERENCES "curriculum_plan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curriculum_plan_item" ADD CONSTRAINT "FK_355807c9012b98c27bd17ee5fe8" FOREIGN KEY ("topic_id") REFERENCES "syllabus"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curriculum_plan" ADD CONSTRAINT "FK_9fac6d5571374d75448d6123800" FOREIGN KEY ("school_id") REFERENCES "school"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curriculum_plan" ADD CONSTRAINT "FK_b46b2bc354ae69219b602173e71" FOREIGN KEY ("academic_year_id") REFERENCES "academic_year"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curriculum_plan" ADD CONSTRAINT "FK_52b5065e60fccdb73a7012fae3b" FOREIGN KEY ("class_id") REFERENCES "class"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curriculum_plan" ADD CONSTRAINT "FK_a5b88100cd96a6035f610d6b5e2" FOREIGN KEY ("subject_id") REFERENCES "subject"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curriculum_mapping" ADD CONSTRAINT "FK_db6dd9dc72a2f0193ea6db8342b" FOREIGN KEY ("school_id") REFERENCES "school"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curriculum_mapping" ADD CONSTRAINT "FK_86095648e937ff3f037189d0065" FOREIGN KEY ("class_id") REFERENCES "class"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curriculum_mapping" ADD CONSTRAINT "FK_ce803be7bade510ff7bb4f5c66c" FOREIGN KEY ("subject_id") REFERENCES "subject"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curriculum_mapping" ADD CONSTRAINT "FK_a96974a40b64f18cd1e687385a9" FOREIGN KEY ("teacher_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curriculum_mapping" ADD CONSTRAINT "FK_2c9e732096680051cb538db35c9" FOREIGN KEY ("lesson_plan_id") REFERENCES "lesson_plans_v3"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "academic_calendar_event" ADD CONSTRAINT "FK_111a60a89f3d2db1db516c49b8b" FOREIGN KEY ("school_id") REFERENCES "school"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "academic_calendar_event" ADD CONSTRAINT "FK_961d218bc77b097105ebcc3f58b" FOREIGN KEY ("academic_year_id") REFERENCES "academic_year"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fee_payment" ADD CONSTRAINT "FK_30812a129a4328ad15bd8f4418e" FOREIGN KEY ("invoice_id") REFERENCES "fee_invoice"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "fee_payment" DROP CONSTRAINT "FK_30812a129a4328ad15bd8f4418e"`);
        await queryRunner.query(`ALTER TABLE "academic_calendar_event" DROP CONSTRAINT "FK_961d218bc77b097105ebcc3f58b"`);
        await queryRunner.query(`ALTER TABLE "academic_calendar_event" DROP CONSTRAINT "FK_111a60a89f3d2db1db516c49b8b"`);
        await queryRunner.query(`ALTER TABLE "curriculum_mapping" DROP CONSTRAINT "FK_2c9e732096680051cb538db35c9"`);
        await queryRunner.query(`ALTER TABLE "curriculum_mapping" DROP CONSTRAINT "FK_a96974a40b64f18cd1e687385a9"`);
        await queryRunner.query(`ALTER TABLE "curriculum_mapping" DROP CONSTRAINT "FK_ce803be7bade510ff7bb4f5c66c"`);
        await queryRunner.query(`ALTER TABLE "curriculum_mapping" DROP CONSTRAINT "FK_86095648e937ff3f037189d0065"`);
        await queryRunner.query(`ALTER TABLE "curriculum_mapping" DROP CONSTRAINT "FK_db6dd9dc72a2f0193ea6db8342b"`);
        await queryRunner.query(`ALTER TABLE "curriculum_plan" DROP CONSTRAINT "FK_a5b88100cd96a6035f610d6b5e2"`);
        await queryRunner.query(`ALTER TABLE "curriculum_plan" DROP CONSTRAINT "FK_52b5065e60fccdb73a7012fae3b"`);
        await queryRunner.query(`ALTER TABLE "curriculum_plan" DROP CONSTRAINT "FK_b46b2bc354ae69219b602173e71"`);
        await queryRunner.query(`ALTER TABLE "curriculum_plan" DROP CONSTRAINT "FK_9fac6d5571374d75448d6123800"`);
        await queryRunner.query(`ALTER TABLE "curriculum_plan_item" DROP CONSTRAINT "FK_355807c9012b98c27bd17ee5fe8"`);
        await queryRunner.query(`ALTER TABLE "curriculum_plan_item" DROP CONSTRAINT "FK_76763a7dae55bc95b9515642736"`);
        await queryRunner.query(`ALTER TABLE "exam_subject" DROP CONSTRAINT "FK_096e1a3aecf719dd5964e33b573"`);
        await queryRunner.query(`ALTER TABLE "homework_submission" DROP CONSTRAINT "FK_ea42144388e4f52a623cb9ddedd"`);
        await queryRunner.query(`ALTER TABLE "inventory_item" DROP CONSTRAINT "FK_4d2125c70a8b37c0d2bca236f40"`);
        await queryRunner.query(`ALTER TABLE "message_thread" DROP CONSTRAINT "FK_70c5b0368192c822fd197144306"`);
        await queryRunner.query(`ALTER TABLE "notification_recipient" DROP CONSTRAINT "FK_f6ebcb1bb7f7f55e33cf8488065"`);
        await queryRunner.query(`ALTER TABLE "planning_calendar" DROP CONSTRAINT "FK_e09b1caf6bf47a24e5d4eead82a"`);
        await queryRunner.query(`ALTER TABLE "planned_schedule" DROP CONSTRAINT "FK_0df06b70ec3b7dcae5a663ab5be"`);
        await queryRunner.query(`ALTER TABLE "planned_schedule" DROP CONSTRAINT "FK_c3946f1eb385e02dd6b39dacc64"`);
        await queryRunner.query(`ALTER TABLE "planned_schedule" DROP CONSTRAINT "FK_54962f5cc9e1bd4bf22b1e4b276"`);
        await queryRunner.query(`ALTER TABLE "planned_schedule" DROP CONSTRAINT "FK_fabfae67b685b6c318a7d531643"`);
        await queryRunner.query(`ALTER TABLE "planned_schedule" DROP CONSTRAINT "FK_e308eba733f6be1ab402d2bd16c"`);
        await queryRunner.query(`ALTER TABLE "planned_schedule" DROP CONSTRAINT "FK_b1c2b3ba3034a3835177dda6252"`);
        await queryRunner.query(`ALTER TABLE "planned_schedule" DROP CONSTRAINT "FK_2fadfa26be2b4160891ad8cb850"`);
        await queryRunner.query(`ALTER TABLE "planned_schedule" DROP CONSTRAINT "FK_11058662640de7fd783447e53e4"`);
        await queryRunner.query(`ALTER TABLE "lesson_plans_v3" DROP CONSTRAINT "FK_48dd2eaa16cf18435a4fe368515"`);
        await queryRunner.query(`ALTER TABLE "lesson_plans_v3" DROP CONSTRAINT "FK_76cbb1cd011b2089abf8a5015d7"`);
        await queryRunner.query(`ALTER TABLE "lesson_plans_v3" DROP CONSTRAINT "FK_cf859f5d7ca538cb0c9c746f008"`);
        await queryRunner.query(`ALTER TABLE "lesson_plans_v3" DROP CONSTRAINT "FK_57f87263653fd68f21303d08dff"`);
        await queryRunner.query(`ALTER TABLE "lesson_plans_v3" DROP CONSTRAINT "FK_96b565574eb7cb6c049d920630f"`);
        await queryRunner.query(`ALTER TABLE "curriculum_units" DROP CONSTRAINT "FK_344206ea52885d57b6b5b495b3f"`);
        await queryRunner.query(`ALTER TABLE "curriculum_units" DROP CONSTRAINT "FK_97b4269e7d7c01c585ab0efe2da"`);
        await queryRunner.query(`ALTER TABLE "report_card" DROP CONSTRAINT "FK_24d288a1b1ea550277955d41b6d"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf"`);
        await queryRunner.query(`ALTER TABLE "school_calendar" DROP CONSTRAINT "FK_23c9ce15950639eba08af82725a"`);
        await queryRunner.query(`ALTER TABLE "school_calendar" DROP CONSTRAINT "FK_91006758c742b253e5c3526061b"`);
        await queryRunner.query(`ALTER TABLE "student_attendance" DROP CONSTRAINT "FK_a042a5b12717cae570c763acbd0"`);
        await queryRunner.query(`ALTER TABLE "student_enrollment" DROP CONSTRAINT "FK_2f5361abfa1e5bc086a51f28bd8"`);
        await queryRunner.query(`ALTER TABLE "student_enrollment" DROP CONSTRAINT "FK_233f8bd7ce6e3c0cd5ba4f6ea4d"`);
        await queryRunner.query(`ALTER TABLE "syllabus" DROP CONSTRAINT "FK_84076f08bebb15b7ae885440ae3"`);
        await queryRunner.query(`ALTER TABLE "syllabus" DROP CONSTRAINT "FK_98f18ccb8e3f01f8051ca8ae477"`);
        await queryRunner.query(`ALTER TABLE "syllabus" DROP CONSTRAINT "FK_76d1df4a0706f0a9436a532d07a"`);
        await queryRunner.query(`ALTER TABLE "syllabus_topic" DROP CONSTRAINT "FK_89a78f9852aa598ca6a5e0805fb"`);
        await queryRunner.query(`ALTER TABLE "teaching_log" DROP CONSTRAINT "FK_1a2f55871a41820e51d9506b470"`);
        await queryRunner.query(`ALTER TABLE "teaching_log" DROP CONSTRAINT "FK_bdf3f3a380ee1cae102cfa1e88a"`);
        await queryRunner.query(`ALTER TABLE "teaching_log" DROP CONSTRAINT "FK_0beaa28dcebe2f458d63e5c9d03"`);
        await queryRunner.query(`ALTER TABLE "teaching_log" DROP CONSTRAINT "FK_2882964b8a6ff3a913435668c18"`);
        await queryRunner.query(`ALTER TABLE "teacher_subject" DROP CONSTRAINT "FK_c876c0444684d4812824989ba2c"`);
        await queryRunner.query(`ALTER TABLE "teacher_subject" DROP CONSTRAINT "FK_7015c3aa4353ae609d1a06492f7"`);
        await queryRunner.query(`ALTER TABLE "teacher_subject" DROP CONSTRAINT "FK_9637c243e0ff941fd4a3389241b"`);
        await queryRunner.query(`ALTER TABLE "teacher_subject" DROP CONSTRAINT "FK_2a9d30cb4207da7ddf7c109097a"`);
        await queryRunner.query(`ALTER TABLE "subject" DROP CONSTRAINT "FK_bbaf2b061bfcebe55de663778cd"`);
        await queryRunner.query(`ALTER TABLE "time_slots" DROP CONSTRAINT "FK_b1ecb91960ccb14bbfe23d06822"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_fb2e442d14add3cefbdf33c4561"`);
        await queryRunner.query(`DROP TABLE "fee_category"`);
        await queryRunner.query(`DROP TABLE "fee_payment"`);
        await queryRunner.query(`DROP TABLE "academic_calendar_event"`);
        await queryRunner.query(`DROP TABLE "academic_plan_item"`);
        await queryRunner.query(`DROP TABLE "analytics_snapshot"`);
        await queryRunner.query(`DROP TABLE "board_config"`);
        await queryRunner.query(`DROP TABLE "curriculum_mapping"`);
        await queryRunner.query(`DROP TABLE "curriculum_plan"`);
        await queryRunner.query(`DROP TABLE "curriculum_plan_item"`);
        await queryRunner.query(`DROP TABLE "exam_subject"`);
        await queryRunner.query(`DROP TABLE "exam_type"`);
        await queryRunner.query(`DROP TABLE "fee_invoice"`);
        await queryRunner.query(`DROP TABLE "fee_structure"`);
        await queryRunner.query(`DROP TABLE "grade_scale"`);
        await queryRunner.query(`DROP TABLE "homework_submission"`);
        await queryRunner.query(`DROP TABLE "homework_assignment"`);
        await queryRunner.query(`DROP TABLE "inventory_item"`);
        await queryRunner.query(`DROP TABLE "message_thread"`);
        await queryRunner.query(`DROP TABLE "message"`);
        await queryRunner.query(`DROP TABLE "notification_recipient"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TABLE "period_configuration"`);
        await queryRunner.query(`DROP TABLE "planning_calendar"`);
        await queryRunner.query(`DROP TABLE "academic_plan"`);
        await queryRunner.query(`DROP TABLE "planned_schedule"`);
        await queryRunner.query(`DROP TYPE "public"."planned_schedule_status_enum"`);
        await queryRunner.query(`DROP TABLE "lesson_plans_v3"`);
        await queryRunner.query(`DROP TABLE "curriculum_units"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_970515f10ff41d260af28738d2"`);
        await queryRunner.query(`DROP TABLE "planning_day"`);
        await queryRunner.query(`DROP TYPE "public"."planning_day_type_enum"`);
        await queryRunner.query(`DROP TABLE "report_card_subject"`);
        await queryRunner.query(`DROP TABLE "report_card"`);
        await queryRunner.query(`DROP TABLE "exam"`);
        await queryRunner.query(`DROP TABLE "role_permission"`);
        await queryRunner.query(`DROP TABLE "permission"`);
        await queryRunner.query(`DROP TABLE "saas_plan"`);
        await queryRunner.query(`DROP TABLE "school_calendar"`);
        await queryRunner.query(`DROP TYPE "public"."school_calendar_day_type_enum"`);
        await queryRunner.query(`DROP TABLE "academic_year"`);
        await queryRunner.query(`DROP TABLE "student_attendance"`);
        await queryRunner.query(`DROP TABLE "attendance_session"`);
        await queryRunner.query(`DROP TABLE "student_document"`);
        await queryRunner.query(`DROP TABLE "student_enrollment"`);
        await queryRunner.query(`DROP TABLE "student_fee_account"`);
        await queryRunner.query(`DROP TABLE "student_guardian"`);
        await queryRunner.query(`DROP TABLE "student_health_record"`);
        await queryRunner.query(`DROP TABLE "student_learning_profile"`);
        await queryRunner.query(`DROP TABLE "student_marks"`);
        await queryRunner.query(`DROP TABLE "student"`);
        await queryRunner.query(`DROP TABLE "syllabus"`);
        await queryRunner.query(`DROP TABLE "syllabus_topic"`);
        await queryRunner.query(`DROP TABLE "teaching_log"`);
        await queryRunner.query(`DROP TABLE "teacher_subject"`);
        await queryRunner.query(`DROP TABLE "subject"`);
        await queryRunner.query(`DROP TABLE "boards"`);
        await queryRunner.query(`DROP TABLE "section"`);
        await queryRunner.query(`DROP TABLE "class"`);
        await queryRunner.query(`DROP TABLE "tenant_subscription"`);
        await queryRunner.query(`DROP TABLE "time_slots"`);
        await queryRunner.query(`DROP TABLE "school"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "role"`);
    }

}
