import { useState } from 'react';
import InsightCard from '../components/InsightCard';
import { demoData } from '../api/client';

export default function AssessmentGenerator() {
    const schoolBoard = demoData.school.affiliationBoard || 'CBSE';
    const role = localStorage.getItem('school_role') || 'principal';

    const [examType, setExamType] = useState('Unit Test 1 (20 Marks)');
    const [subject, setSubject] = useState('Mathematics');
    const [classSelected, setClassSelected] = useState('Class 10');
    const [nepAligned, setNepAligned] = useState(true);
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedExam, setGeneratedExam] = useState(null);

    const getSubjectSections = (subj) => {
        if (subj === 'Mathematics') {
            return [
                { name: 'Section A: Objective (Knowledge)', marks: 10, questions: 10, desc: 'MCQs & Assertion-Reason (Bloom: Remember/Understand)' },
                { name: 'Section B: Short Answer (Application)', marks: 12, questions: 6, desc: 'Formula application (Bloom: Apply)' },
                { name: 'Section C: Case Study (Competency)', marks: 8, questions: 2, desc: 'Real-world problem solving (Bloom: Analyze/Create)' },
                { name: 'Section D: Long Answer (Evaluation)', marks: 10, questions: 2, desc: 'Multi-step proofs (Bloom: Evaluate)' }
            ];
        } else if (subj === 'English') {
            return [
                { name: 'Section A: Reading Comprehension', marks: 10, questions: 1, desc: 'Unseen passage with inference MCQs (Bloom: Analyze)' },
                { name: 'Section B: Writing & Grammar', marks: 10, questions: 3, desc: 'Letter writing & Editing (Bloom: Create/Apply)' },
                { name: 'Section C: Literature', marks: 20, questions: 6, desc: 'Reference to context & Long answers (Bloom: Evaluate)' }
            ];
        }
        // Default generic
        return [
            { name: 'Section A: Objective', marks: 10, questions: 10, desc: 'Multiple Choice' },
            { name: 'Section B: Subjective', marks: 30, questions: 10, desc: 'Short and Long Answers' }
        ];
    };

    const handleGenerate = () => {
        setIsGenerating(true);
        setGeneratedExam(null);
        setTimeout(() => {
            const mockQuestions = subject === 'Mathematics' ? [
                { q: "If the roots of the quadratic equation ax^2 + bx + c = 0 are equal, then what is the value of Discriminant (D)?", marks: 1, type: "Objective (Knowledge)" },
                { q: "Solve for x: 2x^2 - 5x + 3 = 0 using the factorization method.", marks: 3, type: "Short Answer (Application)" },
                { q: "A motorboat whose speed is 18 km/h in still water takes 1 hour more to go 24 km upstream than to return downstream. Find the speed of the stream. Analyze the situation.", marks: 5, type: "Long Answer (Evaluation)" }
            ] : [
                { q: "Read the passage carefully and answer: What is the primary theme discussed by the author in paragraph 2?", marks: 2, type: "Reading Comprehension" },
                { q: "Write a letter to the editor of a local newspaper highlighting the issue of frequent power cuts in your locality.", marks: 5, type: "Writing & Grammar" },
                { q: "Critically analyze the character development of the protagonist in the given chapter.", marks: 5, type: "Literature" }
            ];

            setGeneratedExam({
                id: `EXAM-${Math.floor(Math.random() * 10000)}`,
                date: new Date().toLocaleDateString(),
                title: `${examType.split(' (')[0]} - ${subject} (${schoolBoard})`,
                metadata: `${nepAligned ? 'NEP 2020 Aligned | ' : ''}Competency-Based | ${examType.includes('20') ? '20' : '80'} Marks`,
                sections: getSubjectSections(subject),
                questions: mockQuestions
            });
            setIsGenerating(false);
        }, 1500);
    };

    if (role === 'principal' || role === 'admin') {
        return (
            <div className="page-content">
                <div className="page-header">
                    <div>
                        <h2>✅ Approve Exams</h2>
                        <p>Review and approve AI-generated assessments before publishing.</p>
                    </div>
                </div>
                <div className="card table-card">
                    <table className="data-table">
                        <thead>
                            <tr>
                                <th>Exam Name</th>
                                <th>Generated By</th>
                                <th>Class</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td className="name-cell">Unit Test 1 - Science (CBSE)</td>
                                <td>Mohammed Ali</td>
                                <td>Class 8</td>
                                <td><span className="badge pending">Pending</span></td>
                                <td>
                                    <button className="btn btn-sm btn-primary" style={{ marginRight: 8 }}>Approve</button>
                                    <button className="btn btn-sm btn-secondary">Review</button>
                                </td>
                            </tr>
                            <tr>
                                <td className="name-cell">Half-Yearly - Math (CBSE)</td>
                                <td>Dr. Rajesh Kumar</td>
                                <td>Class 10</td>
                                <td><span className="badge pending">Pending</span></td>
                                <td>
                                    <button className="btn btn-sm btn-primary" style={{ marginRight: 8 }}>Approve</button>
                                    <button className="btn btn-sm btn-secondary">Review</button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        );
    }

    return (
        <div className="page-content">
            <div className="page-header">
                <div>
                    <h2>📝 Exam Generator</h2>
                    <p>Auto-generate board-compliant, subject-specific exams tracking Bloom's Taxonomy.</p>
                </div>
            </div>

            <div className="charts-grid" style={{ gridTemplateColumns: 'minmax(300px, 1fr) 2fr', alignItems: 'start' }}>
                <div className="card" style={{ padding: 24 }}>
                    <h3 style={{ marginBottom: 20 }}>Exam Settings</h3>

                    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                        <div>
                            <label style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8, fontSize: 13, fontWeight: 600 }}>
                                <span>Education Board</span>
                                <span style={{ color: 'var(--text-muted)', fontSize: 11 }}>Locked to School Mappings</span>
                            </label>
                            <input className="form-input" disabled value={`${schoolBoard} (Assigned by Admin)`} style={{ background: 'var(--bg-secondary)', color: 'var(--text-muted)', cursor: 'not-allowed' }} />
                        </div>

                        <div>
                            <label style={{ display: 'block', marginBottom: 8, fontSize: 13, fontWeight: 600 }}>Class / Grade</label>
                            <select className="form-input" style={{ appearance: 'auto' }} value={classSelected} onChange={(e) => setClassSelected(e.target.value)}>
                                <option>Class 12</option>
                                <option>Class 10</option>
                                <option>Class 9</option>
                                <option>Class 8</option>
                            </select>
                        </div>

                        <div>
                            <label style={{ display: 'block', marginBottom: 8, fontSize: 13, fontWeight: 600 }}>Subject</label>
                            <select className="form-input" style={{ appearance: 'auto' }} value={subject} onChange={(e) => setSubject(e.target.value)}>
                                <option>Mathematics</option>
                                <option>English</option>
                                <option>Science</option>
                                <option>Social Studies</option>
                            </select>
                        </div>

                        <div>
                            <label style={{ display: 'block', marginBottom: 8, fontSize: 13, fontWeight: 600 }}>Exam Format</label>
                            <select className="form-input" style={{ appearance: 'auto' }} value={examType} onChange={(e) => setExamType(e.target.value)}>
                                <option>Unit Test 1 (20 Marks)</option>
                                <option>Half-Yearly Exam (80 Marks)</option>
                                <option>Annual Exam (80 Marks)</option>
                                {(classSelected === 'Class 10' || classSelected === 'Class 12') && <option style={{ fontWeight: 700 }}>Mock Board Exam (Full Syllabus)</option>}
                            </select>
                        </div>

                        <label style={{ display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer', marginTop: 8 }}>
                            <input type="checkbox" checked={nepAligned} onChange={(e) => setNepAligned(e.target.checked)} />
                            <span style={{ fontSize: 13, lineHeight: '1.4' }}>Align with NEP 2020 Framework <br /><span style={{ color: 'var(--text-muted)', fontSize: 11 }}>(Integrate Competency & Critical Thinking)</span></span>
                        </label>

                        <button className="btn btn-primary" style={{ width: '100%', marginTop: 12 }} onClick={handleGenerate} disabled={isGenerating}>
                            {isGenerating ? '🧠 Analyzing Pedagogy...' : '✨ Create Blueprint'}
                        </button>
                    </div>
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
                    <InsightCard
                        type="highlight"
                        icon="📐"
                        title={`${subject} Specific Guidelines`}
                        body={subject === 'Mathematics' ? `Applying analytical tracking. Case-study questions will be weighted heavier on Application and Validation.` : subject === 'English' ? `Applying language tracking. Emphasis placed on Unseen Inference and Creative writing formulation.` : `Standard cognitive load balancing applied.`}
                    />

                    {isGenerating && (
                        <div className="card" style={{ padding: 48, textAlign: 'center' }}>
                            <div style={{ fontSize: 48, marginBottom: 16 }} className="spin-animation">⚙️</div>
                            <h3>Mapping {subject} Learning Outcomes...</h3>
                            <p style={{ color: 'var(--text-muted)' }}>Generating DOK-coded questions for {schoolBoard} pattern.</p>
                        </div>
                    )}

                    {generatedExam && (
                        <div className="card" style={{ padding: 32, border: '2px solid var(--accent)', transition: 'all 0.3s ease' }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '1px solid var(--border)', paddingBottom: 16, marginBottom: 24 }}>
                                <div>
                                    <div style={{ display: 'flex', gap: 8, marginBottom: 8 }}>
                                        <span className="badge active">{classSelected}</span>
                                        <span className="badge" style={{ background: 'var(--bg-secondary)', color: 'var(--text-secondary)' }}>{generatedExam.metadata}</span>
                                    </div>
                                    <h2 style={{ margin: '8px 0', color: 'var(--text-primary)' }}>{generatedExam.title}</h2>
                                    <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>ID: {generatedExam.id} • Generated: {generatedExam.date}</div>
                                </div>
                                <div style={{ display: 'flex', gap: 12 }}>
                                    <button className="btn btn-secondary">Edit Questions</button>
                                    <button className="btn btn-primary">Export PDF</button>
                                </div>
                            </div>

                            <div style={{ display: 'grid', gap: 16 }}>
                                {generatedExam.sections.map((sec, i) => (
                                    <div key={i} style={{ padding: 16, background: 'var(--bg-primary)', borderRadius: 'var(--radius-sm)', border: '1px solid var(--border)', display: 'flex', flexDirection: 'column', gap: 8 }}>
                                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                            <h4 style={{ margin: 0, color: 'var(--success)' }}>{sec.name}</h4>
                                            <span style={{ fontWeight: 600, fontSize: 14 }}>{sec.marks} Marks</span>
                                        </div>
                                        <div style={{ fontSize: 13, color: 'var(--text-secondary)' }}>
                                            {sec.questions} Questions • <span style={{ fontStyle: 'italic', fontWeight: 500 }}>{sec.desc}</span>
                                        </div>
                                    </div>
                                ))}
                            </div>

                            <div style={{ marginTop: 32 }}>
                                <h3 style={{ borderBottom: '1px solid var(--border)', paddingBottom: 8, marginBottom: 16 }}>Actual Generated Questions (Review Mode)</h3>
                                <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                                    {generatedExam.questions.map((q, i) => (
                                        <div key={i} style={{ padding: 16, background: 'var(--bg-primary)', borderRadius: 'var(--radius-sm)', border: '1px solid var(--border)' }}>
                                            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8 }}>
                                                <span style={{ fontWeight: 600, fontSize: 13, color: 'var(--text-muted)' }}>Question {i + 1} • {q.type}</span>
                                                <span style={{ fontWeight: 700, fontSize: 13, color: 'var(--accent)' }}>[{q.marks} Marks]</span>
                                            </div>
                                            <div style={{ fontSize: 15, lineHeight: 1.5, color: 'var(--text-primary)' }}>{q.q}</div>
                                            <div style={{ marginTop: 12, display: 'flex', gap: 8 }}>
                                                <button className="btn btn-sm btn-secondary" style={{ padding: '4px 12px', fontSize: 12 }}>✏️ Edit</button>
                                                <button className="btn btn-sm btn-secondary" style={{ padding: '4px 12px', fontSize: 12, color: 'var(--danger)' }}>🗑️ Remove</button>
                                                <button className="btn btn-sm btn-secondary" style={{ padding: '4px 12px', fontSize: 12 }}>🔄 Regenerate</button>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                                <div style={{ marginTop: 24, textAlign: 'right' }}>
                                    <button className="btn btn-primary">Submit for Principal Approval</button>
                                </div>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
